on:
  push: ["master"]
  pull_request: ["master"]

jobs:
  test_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    - name: Build
      run: |
        gcc examples/hello_world/hello.c -o hello_world
        
    - name: Run
      run: |
        python3 -m YAMLscan hello_world examples/hello_world/rule.yaml
        python3 -m YAMLscan examples/ip_address/ip.txt examples/ip_address/rule.yaml